// Generated by Framer (2ac8f15)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    Container,
    cx,
    GeneratedComponentContext,
    getFonts,
    getPropertyControls,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Nav from "#framer/local/canvasComponent/OQHl4W67S/OQHl4W67S.js";
import Footer from "#framer/local/canvasComponent/xSw0JeNIq/xSw0JeNIq.js";
const NavFonts = getFonts(Nav);
const ContainerWithFX = withFX(Container);
const FooterFonts = getFonts(Footer);
const NavControls = getPropertyControls(Nav);
const breakpoints = {
    AhYgnuW4O: "(max-width: 809px)",
    l0yNcxlX1: "(min-width: 1200px)",
    y95rf3Giw: "(min-width: 810px) and (max-width: 1199px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-8rl7i";
const variantClassNames = {
    AhYgnuW4O: "framer-v-rxwgra",
    l0yNcxlX1: "framer-v-9odv1x",
    y95rf3Giw: "framer-v-2msyhx"
};
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const animation = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: -128
};
const breakpointRules = {
    AhYgnuW4O: [".framer-8rl7i .framer-10eppty-container { left: 23px; right: 23px; top: 23px; }"]
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    AhYgnuW4O: ".framer-rxwgra-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-8rl7i.framer-1518fa, .framer-8rl7i .framer-1518fa { display: block; }", ".framer-8rl7i.framer-9odv1x { align-content: center; align-items: center; background-color: #ffffff; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-8rl7i .framer-10eppty-container { flex: none; height: auto; left: 48px; position: var(--framer-canvas-fixed-position, fixed); right: 48px; top: 48px; z-index: 10; }", ".framer-8rl7i .framer-1y69pcl { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }", ".framer-8rl7i .framer-kmg2re-container { flex: none; height: auto; order: 1002; position: relative; width: 100%; }", '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }'];
const mediaQueries = {
    AhYgnuW4O: "(max-width: 809px)",
    l0yNcxlX1: "(min-width: 1200px)",
    y95rf3Giw: "(min-width: 810px) and (max-width: 1199px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableEnumMap = {
    "Desktop - About": "yPLSD6SVP",
    "Desktop - Contact": "XkKt9gos4",
    "Desktop - Default": "mcLTa3Wrv",
    "Desktop - Home": "xrS1ceA1M",
    "Desktop - Projects": "ChoaQAbXA",
    "Desktop - Services": "EHw5s6SWN",
    "Mobile - About - Opened": "L50m7va0G",
    "Mobile - About": "wutNmj65q",
    "Mobile - Contact - Opened": "n4Qy6N8lY",
    "Mobile - Contact": "rkpryZigP",
    "Mobile - Default": "cCe6P8qAp",
    "Mobile - Home - Opened": "SlEzLgn0B",
    "Mobile - Home": "w5oxjoCgT",
    "Mobile - Projects - Opened": "zzf_lfiC2",
    "Mobile - Projects": "UgLdg1NeQ",
    "Mobile - Services - Opened": "UkUXgsiHu",
    "Mobile - Services": "SJ9sRCVld",
    "Mobile Default - Opened": "YxoVoXy7L"
};
const humanReadableVariantMap = {
    Desktop: "l0yNcxlX1",
    Phone: "AhYgnuW4O",
    Tablet: "y95rf3Giw"
};
const getProps = ({
    desktop,
    height,
    id,
    mobile,
    width,
    ...props
}) => {
    return { ...props,
        eZFFqciAN: humanReadableEnumMap[desktop] ? ? desktop ? ? props.eZFFqciAN ? ? "mcLTa3Wrv",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "l0yNcxlX1",
        YttmXIAHE: humanReadableEnumMap[mobile] ? ? mobile ? ? props.YttmXIAHE ? ? "cCe6P8qAp"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        eZFFqciAN,
        YttmXIAHE,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "l0yNcxlX1",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: rgb(255, 255, 255); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-9odv1x", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                        AhYgnuW4O: {
                            width: "calc(100vw - 46px)",
                            y: 23
                        }
                    },
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 80,
                        width: "calc(100vw - 96px)",
                        y: 48,
                        children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                            __framer__animate: {
                                transition: transition1
                            },
                            __framer__animateOnce: false,
                            __framer__scrollDirection: {
                                direction: "down",
                                target: animation
                            },
                            __framer__styleAppearEffectEnabled: true,
                            __framer__threshold: .5,
                            __perspectiveFX: false,
                            __targetOpacity: 1,
                            className: "framer-10eppty-container",
                            layoutScroll: true,
                            nodeId: "OJCHir3uB",
                            rendersWithMotion: true,
                            scopeId: "AwZXMVBl9",
                            children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                breakpoint: baseVariant,
                                overrides: {
                                    AhYgnuW4O: {
                                        variant: YttmXIAHE
                                    },
                                    y95rf3Giw: {
                                        variant: YttmXIAHE
                                    }
                                },
                                children: /*#__PURE__*/ _jsx(Nav, {
                                    height: "100%",
                                    id: "OJCHir3uB",
                                    layoutId: "OJCHir3uB",
                                    style: {
                                        width: "100%"
                                    },
                                    variant: eZFFqciAN,
                                    width: "100%"
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-1y69pcl"
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 533,
                    width: "100vw",
                    y: 1e3,
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-kmg2re-container",
                        nodeId: "z4oINNjPc",
                        scopeId: "AwZXMVBl9",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                AhYgnuW4O: {
                                    variant: "ar9rRlxLY"
                                },
                                y95rf3Giw: {
                                    variant: "kuTfhk8lT"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Footer, {
                                height: "100%",
                                id: "z4oINNjPc",
                                layoutId: "z4oINNjPc",
                                style: {
                                    width: "100%"
                                },
                                variant: "pPB1w7yVl",
                                width: "100%"
                            })
                        })
                    })
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 2200
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"y95rf3Giw":{"layout":["fixed","fixed"]},"AhYgnuW4O":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"eZFFqciAN":"desktop","YttmXIAHE":"mobile"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"l0yNcxlX1":[".framer-10eppty-container",".framer-kmg2re-container"],"y95rf3Giw":[".framer-10eppty-container",".framer-kmg2re-container"],"AhYgnuW4O":[".framer-10eppty-container",".framer-kmg2re-container"]}
 * @framerBreakpoints {"l0yNcxlX1":{"min":1200,"canvasClassName":"framer-9odv1x-override","minHeight":2200,"name":"Desktop","width":1200,"rootFontSize":16},"y95rf3Giw":{"min":810,"max":1199,"canvasClassName":"framer-2msyhx-override","minHeight":2200,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"AhYgnuW4O":{"max":809,"canvasClassName":"framer-rxwgra-override","minHeight":2200,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant l0yNcxlX1
 * @framerLayoutTemplate
 */
const FramerAwZXMVBl9 = withCSS(Component, css, "framer-8rl7i");
export default FramerAwZXMVBl9;
FramerAwZXMVBl9.displayName = "Main Default";
FramerAwZXMVBl9.defaultProps = {
    height: 2200,
    width: 1200
};
addPropertyControls(FramerAwZXMVBl9, {
    eZFFqciAN: NavControls ? .["variant"] && { ...NavControls["variant"],
        defaultValue: "mcLTa3Wrv",
        description: undefined,
        hidden: undefined,
        title: "Desktop"
    },
    YttmXIAHE: NavControls ? .["variant"] && { ...NavControls["variant"],
        defaultValue: "cCe6P8qAp",
        description: undefined,
        hidden: undefined,
        title: "Mobile"
    }
});
addFonts(FramerAwZXMVBl9, [{
    explicitInter: true,
    fonts: []
}, ...NavFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerAwZXMVBl9",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "1200",
                "framerBreakpoints": "{\"l0yNcxlX1\":{\"min\":1200,\"canvasClassName\":\"framer-9odv1x-override\",\"minHeight\":2200,\"name\":\"Desktop\",\"width\":1200,\"rootFontSize\":16},\"y95rf3Giw\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-2msyhx-override\",\"minHeight\":2200,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"AhYgnuW4O\":{\"max\":809,\"canvasClassName\":\"framer-rxwgra-override\",\"minHeight\":2200,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":390,\"rootFontSize\":16}}",
                "framerLayoutTemplate": "",
                "framerVariables": "{\"eZFFqciAN\":\"desktop\",\"YttmXIAHE\":\"mobile\"}",
                "framerIntrinsicHeight": "2200",
                "framerColorSyntax": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"y95rf3Giw\":{\"layout\":[\"fixed\",\"fixed\"]},\"AhYgnuW4O\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerHitTargets": "{\"l0yNcxlX1\":[\".framer-10eppty-container\",\".framer-kmg2re-container\"],\"y95rf3Giw\":[\".framer-10eppty-container\",\".framer-kmg2re-container\"],\"AhYgnuW4O\":[\".framer-10eppty-container\",\".framer-kmg2re-container\"]}",
                "framerDefaultVariant": "l0yNcxlX1",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}