// Generated by Framer (92d6359)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-mCwQTIofB", breakpoints: [{hash: "he08am", mediaQuery: "(min-width: 1200px)"}, {hash: "1q4tqff", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "sc9ayj", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-RNV8x", title: siteMetadata(params, activeLocale).title || "Policies", viewport: "width=device-width"}
}

export const metadataVersion = 1