// Generated by Framer (ca9141d)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-jap6GJY1y", breakpoints: [{hash: "1j13q3c", mediaQuery: "(min-width: 1200px)"}, {hash: "1bhno8s", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "15eguzt", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {DIqD4xsQt: "how-its-made", o9OhFBtxF: "interior-design", q_jjA0t3A: "Residential Design", z3Kdx6weZ: "commercial-design"}, robots: "max-image-preview:large", serializationId: "framer-mmpOK", title: siteMetadata(params, activeLocale).title || "Services", viewport: "width=device-width"}
}

export const metadataVersion = 1