// Generated by Framer (4240133)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-j5l5YwPZG", breakpoints: [{hash: "1uitexc", mediaQuery: "(min-width: 1200px)"}, {hash: "96mpfb", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "boqg68", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-DAsKK", title: siteMetadata(params, activeLocale).title || "Contact", viewport: "width=device-width"}
}

export const metadataVersion = 1