// Generated by Framer (b4533c2)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {NZU30mNfX: {v0: ({ zK6oKDpVa }) => `${zK6oKDpVa !== undefined ? toString(zK6oKDpVa) : "{{zK6oKDpVa}}"} - EVIVE - Šablona designu architektury`}}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const zK6oKDpVa = params?.zK6oKDpVa
return {breakpoints: [{hash: "1hnocr6", mediaQuery: "(min-width: 1200px)"}, {hash: "3lwtd7", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "hu1nv1", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {kSRocSzsL: "residential-design", N0oqJi_Ms: "newsletter", q0LIW_OQ9: "residential-design-1", w7V7GrIvr: "residential-design-2"}, robots: "max-image-preview:large", serializationId: "framer-evTqo", title: getLocalizedValue("v0", activeLocale)?.({ zK6oKDpVa }) ?? `${zK6oKDpVa !== undefined ? toString(zK6oKDpVa) : "{{zK6oKDpVa}}"} - EVIVE - Arch Design Template`, viewport: "width=device-width"}
}

export const metadataVersion = 1