// Generated by Framer (62acaa8)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {Ht7Bum79U: {v0: ({ KR9ciHCpe }) => `${KR9ciHCpe !== undefined ? toString(KR9ciHCpe) : "{{KR9ciHCpe}}"} - EVIVE - Šablona Arch Design`}}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const KR9ciHCpe = params?.KR9ciHCpe
return {breakpoints: [{hash: "15qdkmh", mediaQuery: "(min-width: 1200px)"}, {hash: "1p3r0qm", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "12jhok5", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {sZ57fvbP6: "newsletter"}, robots: "max-image-preview:large", serializationId: "framer-5nRAs", title: getLocalizedValue("v0", activeLocale)?.({ KR9ciHCpe }) ?? `${KR9ciHCpe !== undefined ? toString(KR9ciHCpe) : "{{KR9ciHCpe}}"} - EVIVE - Arch Design Template`, viewport: "width=device-width"}
}

export const metadataVersion = 1