// Generated by Framer (03f754e)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-mYYQ1vlHX", breakpoints: [{hash: "teqvgz", mediaQuery: "(min-width: 1200px)"}, {hash: "ptzo0q", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "su6mz7", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-mSM2g", title: siteMetadata(params, activeLocale).title || "Projects", viewport: "width=device-width"}
}

export const metadataVersion = 1