// Generated by Framer (e010222)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-iKcjAD09W", breakpoints: [{hash: "1jyn3b2", mediaQuery: "(min-width: 1200px)"}, {hash: "ogc8i4", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1q7f6nd", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {YTFGjHUNS: "newsletter"}, robots: "max-image-preview:large", serializationId: "framer-XyBI9", title: siteMetadata(params, activeLocale).title || "Categories", viewport: "width=device-width"}
}

export const metadataVersion = 1