// Generated by Framer (62acaa8)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {Ht7Bum79U: {v0: ({ Pg_y2qV1V }) => `${Pg_y2qV1V !== undefined ? toString(Pg_y2qV1V) : "{{Pg_y2qV1V}}"} - EVIVE - Arch Design Šablona`}}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const Pg_y2qV1V = params?.Pg_y2qV1V
return {breakpoints: [{hash: "bkdkr7", mediaQuery: "(min-width: 1200px)"}, {hash: "1ir7xbx", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "i39j98", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {tBc0px1if: "newsletter"}, robots: "max-image-preview:large", serializationId: "framer-kBvcn", title: getLocalizedValue("v0", activeLocale)?.({ Pg_y2qV1V }) ?? `${Pg_y2qV1V !== undefined ? toString(Pg_y2qV1V) : "{{Pg_y2qV1V}}"} - EVIVE - Arch Design Template`, viewport: "width=device-width"}
}

export const metadataVersion = 1