// Generated by Framer (98479f1)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-Gp8we21Ys", breakpoints: [{hash: "5n9zza"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-WBJAc", title: siteMetadata(params, activeLocale).title || "Projects 2", viewport: "width=1200"}
}

export const metadataVersion = 1