// Generated by Framer (e4277c8)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-AK4QAs1x5", breakpoints: [{hash: "tk47e1", mediaQuery: "(min-width: 1200px)"}, {hash: "1l00h59", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "yxqh6e", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-PHEfq", title: siteMetadata(params, activeLocale).title || "Services", viewport: "width=device-width"}
}

export const metadataVersion = 1