// Generated by Framer (92d6359)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-fhlB736y6", breakpoints: [{hash: "5p51mr"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-oxAGY", title: siteMetadata(params, activeLocale).title || "Projects", viewport: "width=1200"}
}

export const metadataVersion = 1