// Generated by Framer (98479f1)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-trzXN4KJo", breakpoints: [{hash: "hstzsf"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-o6ErI", title: siteMetadata(params, activeLocale).title || "Projects 2", viewport: "width=1200"}
}

export const metadataVersion = 1