// Generated by Framer (98479f1)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-HO7G4ngO4", breakpoints: [{hash: "ncbt6o"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-CScks", title: siteMetadata(params, activeLocale).title || "Projects", viewport: "width=1200"}
}

export const metadataVersion = 1