// Generated by Framer (92d6359)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const zK6oKDpVa = params?.zK6oKDpVa
return {bodyClassName: "framer-body-OH8KRxQMo", breakpoints: [{hash: "1s65578"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-IOnVY", title: `${zK6oKDpVa !== undefined ? toString(zK6oKDpVa) : "{{zK6oKDpVa}}"} - My Framer Site`, viewport: "width=1200"}
}

export const metadataVersion = 1