// Generated by Framer (a2fb474)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const zK6oKDpVa = params?.zK6oKDpVa
return {bodyClassName: "framer-body-YSjlkabnN", breakpoints: [{hash: "9gwq10", mediaQuery: "(min-width: 1200px)"}, {hash: "1osdbfs", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1ya26oe", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-cR5We", title: `${zK6oKDpVa !== undefined ? toString(zK6oKDpVa) : "{{zK6oKDpVa}}"} - My Framer Site`, viewport: "width=device-width"}
}

export const metadataVersion = 1