// Generated by Framer (b4533c2)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1j90feh", mediaQuery: "(min-width: 1200px)"}, {hash: "1ciqyq", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "9ywxdh", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {BZg81ZBKH: "interior-design", Fpey5OcDd: "newsletter", JB1uDc5Mo: "how-it-s-made-01", JgKkXtDP0: "how-it-s-made-02", L4H07_dDi: "residential-design", ZQXZcokfS: "commercial-design"}, robots: "max-image-preview:large", serializationId: "framer-itCdJ", title: siteMetadata(params, activeLocale).title || "Services", viewport: "width=device-width"}
}

export const metadataVersion = 1