// Generated by Framer (e010222)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-IT7Zx793O", breakpoints: [{hash: "d93br4", mediaQuery: "(min-width: 1200px)"}, {hash: "1ohv0e4", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "19ar302", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {NavhPPlEx: "newsletter"}, robots: "max-image-preview:large", serializationId: "framer-TANyb", title: siteMetadata(params, activeLocale).title || "Projects", viewport: "width=device-width"}
}

export const metadataVersion = 1