// Generated by Framer (c90df04)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
const cycleOrder = ["XTyZS4MpB", "aYA2dZuo5"];
const serializationHash = "framer-u8Aii";
const variantClassNames = {
    aYA2dZuo5: "framer-v-1jx1ofi",
    XTyZS4MpB: "framer-v-11u7wwq"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants === null || variants === void 0 ? void 0 : variants.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value !== null && value !== void 0 ? value : config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Close: "aYA2dZuo5",
    Default: "XTyZS4MpB"
};
const getProps = ({
    click,
    height,
    id,
    width,
    ...props
}) => {
    var _humanReadableVariantMap_props_variant, _ref;
    return { ...props,
        AR4mury4J: click !== null && click !== void 0 ? click : props.AR4mury4J,
        variant: (_ref = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref !== void 0 ? _ref : "XTyZS4MpB"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        AR4mury4J,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "XTyZS4MpB",
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap933xpe = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (AR4mury4J) {
            const res = await AR4mury4J(...args);
            if (res === false) return false;
        }
    });
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const sharedStyleClassNames = [];
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(serializationHash, ...sharedStyleClassNames, "framer-11u7wwq", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "XTyZS4MpB",
                    onTap: onTap933xpe,
                    ref: ref !== null && ref !== void 0 ? ref : ref1,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        aYA2dZuo5: {
                            "data-framer-name": "Close"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1g2vpwi",
                        layoutDependency: layoutDependency,
                        layoutId: "RM95aauRz",
                        style: {
                            backgroundColor: "var(--token-7f09362c-5ec1-40a3-9549-f3af082a64fe, rgb(0, 0, 0))",
                            rotate: 0
                        },
                        variants: {
                            aYA2dZuo5: {
                                rotate: 45
                            }
                        }
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-b9gbwx",
                        layoutDependency: layoutDependency,
                        layoutId: "bhJwNY8tE",
                        style: {
                            backgroundColor: "var(--token-7f09362c-5ec1-40a3-9549-f3af082a64fe, rgb(0, 0, 0))",
                            rotate: 0
                        },
                        variants: {
                            aYA2dZuo5: {
                                rotate: -45
                            }
                        }
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-u8Aii.framer-1elgclv, .framer-u8Aii .framer-1elgclv { display: block; }", ".framer-u8Aii.framer-11u7wwq { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 24px; }", ".framer-u8Aii .framer-1g2vpwi { flex: none; height: 1px; left: calc(50.00000000000002% - 24px / 2); overflow: hidden; position: absolute; top: 8px; width: 24px; z-index: 1; }", ".framer-u8Aii .framer-b9gbwx { bottom: 8px; flex: none; height: 1px; left: 0px; overflow: hidden; position: absolute; right: 0px; z-index: 1; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-u8Aii.framer-11u7wwq { gap: 0px; } .framer-u8Aii.framer-11u7wwq > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-u8Aii.framer-11u7wwq > :first-child { margin-top: 0px; } .framer-u8Aii.framer-11u7wwq > :last-child { margin-bottom: 0px; } }", ".framer-u8Aii.framer-v-1jx1ofi .framer-1g2vpwi { top: calc(50.00000000000002% - 1px / 2); }", ".framer-u8Aii.framer-v-1jx1ofi .framer-b9gbwx { bottom: unset; left: calc(50.00000000000002% - 24px / 2); right: unset; top: calc(50.00000000000002% - 1px / 2); width: 24px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 24
 * @framerIntrinsicWidth 24
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"aYA2dZuo5":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"AR4mury4J":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const Framerv8Vx148wp = withCSS(Component, css, "framer-u8Aii");
export default Framerv8Vx148wp;
Framerv8Vx148wp.displayName = "Menu";
Framerv8Vx148wp.defaultProps = {
    height: 24,
    width: 24
};
addPropertyControls(Framerv8Vx148wp, {
    variant: {
        options: ["XTyZS4MpB", "aYA2dZuo5"],
        optionTitles: ["Default", "Close"],
        title: "Variant",
        type: ControlType.Enum
    },
    AR4mury4J: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(Framerv8Vx148wp, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framerv8Vx148wp",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "24",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"aYA2dZuo5\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"AR4mury4J\":\"click\"}",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "24"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./v8Vx148wp.map