// Generated by Framer (62acaa8)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "vvfvjr", mediaQuery: "(min-width: 1200px)"}, {hash: "1g76nwx", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1fckyjp", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {sD06N9wlM: "newsletter"}, robots: "max-image-preview:large", serializationId: "framer-qyp19", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1