// Generated by Framer (e4e7123)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const KR9ciHCpe = params?.KR9ciHCpe
return {bodyClassName: "framer-body-QtMcGIfK2", breakpoints: [{hash: "juai91", mediaQuery: "(min-width: 1200px)"}, {hash: "k9jgto", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "h75ze3", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-GUL6a", title: `${KR9ciHCpe !== undefined ? toString(KR9ciHCpe) : "{{KR9ciHCpe}}"} - My Framer Site`, viewport: "width=device-width"}
}

export const metadataVersion = 1