// Generated by Framer (98479f1)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-YRP7ToO4_", breakpoints: [{hash: "pz7gln"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-z7p48", title: siteMetadata(params, activeLocale).title || "Projects", viewport: "width=1200"}
}

export const metadataVersion = 1