// Generated by Framer (48da836)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = ['.framer-jLsQ0 .framer-styles-preset-1pynx46:not(.rich-text-wrapper), .framer-jLsQ0 .framer-styles-preset-1pynx46.rich-text-wrapper a { --framer-link-current-text-color: var(--token-10cd1b53-40b5-4cbc-bcaf-2cb07aba87a4, #b3b3b3) /* {"name":"Light 70"} */; --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-8bc845a9-937a-4bbd-ad58-ebae6a54d231, #ffffff) /* {"name":"White"} */; --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-10cd1b53-40b5-4cbc-bcaf-2cb07aba87a4, #b3b3b3); --framer-link-text-decoration: none; }'];
export const className = "framer-jLsQ0";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}