// Generated by Framer (b4533c2)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/5DAljcQBVvmJbOtkIdld/rp7j7FvDJfMPVLCDazST/BzFif7mYe.js";
import * as sharedStyle from "https://framerusercontent.com/modules/8Qwy1C20190W3EguxhII/BdZSMslRBoeW4t5l06ca/Wn1jSaZfC.js";
const cycleOrder = ["c9iKqzOsB", "JQOkHqNdb"];
const serializationHash = "framer-rHE6l";
const variantClassNames = {
    c9iKqzOsB: "framer-v-13vgxr3",
    JQOkHqNdb: "framer-v-t5fmct"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Center: "JQOkHqNdb",
    Left: "c9iKqzOsB"
};
const getProps = ({
    height,
    id,
    name1,
    role,
    width,
    ...props
}) => {
    return { ...props,
        eGfKwtR52: name1 ? ? props.eGfKwtR52 ? ? "Emil Vysok\xfd",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "c9iKqzOsB",
        zgfzggQKb: role ? ? props.zgfzggQKb ? ? "Senior Achitect"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        eGfKwtR52,
        zgfzggQKb,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "c9iKqzOsB",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-13vgxr3", className, classNames),
                    "data-framer-name": "Left",
                    layoutDependency: layoutDependency,
                    layoutId: "c9iKqzOsB",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        JQOkHqNdb: {
                            "data-framer-name": "Center"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-vuakil",
                                "data-styles-preset": "Wn1jSaZfC",
                                children: "Ethan Walker"
                            })
                        }),
                        className: "framer-zfjrrm",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "VG_3FhsyY",
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: eGfKwtR52,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            JQOkHqNdb: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-vuakil",
                                        "data-styles-preset": "Wn1jSaZfC",
                                        style: {
                                            "--framer-text-alignment": "center"
                                        },
                                        children: "Ethan Walker"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-7d6d2n",
                                "data-styles-preset": "BzFif7mYe",
                                children: "Senior Achitect"
                            })
                        }),
                        className: "framer-1696sj4",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "i6iavWNWZ",
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: zgfzggQKb,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            JQOkHqNdb: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-7d6d2n",
                                        "data-styles-preset": "BzFif7mYe",
                                        style: {
                                            "--framer-text-alignment": "center"
                                        },
                                        children: "Senior Achitect"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-rHE6l.framer-6s5l8m, .framer-rHE6l .framer-6s5l8m { display: block; }", ".framer-rHE6l.framer-13vgxr3 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 158px; }", ".framer-rHE6l .framer-zfjrrm, .framer-rHE6l .framer-1696sj4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 43
 * @framerIntrinsicWidth 158
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"JQOkHqNdb":{"layout":["fixed","auto"]}}}
 * @framerVariables {"eGfKwtR52":"name1","zgfzggQKb":"role"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerHzL36FQD5 = withCSS(Component, css, "framer-rHE6l");
export default FramerHzL36FQD5;
FramerHzL36FQD5.displayName = "Name and Role";
FramerHzL36FQD5.defaultProps = {
    height: 43,
    width: 158
};
addPropertyControls(FramerHzL36FQD5, {
    variant: {
        options: ["c9iKqzOsB", "JQOkHqNdb"],
        optionTitles: ["Left", "Center"],
        title: "Variant",
        type: ControlType.Enum
    },
    eGfKwtR52: {
        defaultValue: "Emil Vysok\xfd",
        displayTextArea: false,
        title: "Name",
        type: ControlType.String
    },
    zgfzggQKb: {
        defaultValue: "Senior Achitect",
        displayTextArea: false,
        title: "Role",
        type: ControlType.String
    }
});
addFonts(FramerHzL36FQD5, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerHzL36FQD5",
            "slots": [],
            "annotations": {
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"JQOkHqNdb\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "43",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"eGfKwtR52\":\"name1\",\"zgfzggQKb\":\"role\"}",
                "framerIntrinsicWidth": "158",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./HzL36FQD5.map