// Generated by Framer (ca9141d)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-GE6XnsNdo", breakpoints: [{hash: "1kuidtn", mediaQuery: "(min-width: 1200px)"}, {hash: "fe8k0j", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1t87nc3", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {FWlRF_c_d: "functionality", FXbnsuL1J: "balance", OM2Heoz_D: "the-team", Uup8MC9Q4: "aesthetics", vSAv5vrXS: "who-we-are"}, robots: "max-image-preview:large", serializationId: "framer-pogrl", title: siteMetadata(params, activeLocale).title || "About", viewport: "width=device-width"}
}

export const metadataVersion = 1