// Generated by Framer (48da836)

import { addFonts, addPropertyControls, ControlType, cx, CycleVariantState, getFontsFromSharedStyle, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import * as sharedStyle1 from "../css/tTKYWLQt6";
import * as sharedStyle from "../css/xmi7mkoo2";

const serializationHash = "framer-7uuAn"

const variantClassNames = {zxRR1dag8: "framer-v-hxggjt"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {bounce: 0.2, delay: 0, duration: 0.4, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const getProps = ({height, id, number, title, width, ...props}) => { return {...props, w2mTfVwjE: title ?? props.w2mTfVwjE ?? "Years Experience", wwN2FoqAa: number ?? props.wwN2FoqAa ?? "12"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;number?: string;title?: string; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const { activeLocale, setLocale } = useLocaleInfo()

const {style, className, layoutId, variant, wwN2FoqAa, w2mTfVwjE, ...restProps} = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({defaultVariant: "zxRR1dag8", variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className]

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

const ref1 = React.useRef<HTMLElement>(null)

const defaultLayoutId = React.useId()

const componentViewport = useComponentViewport()

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-hxggjt", className, classNames)} data-framer-name={"Default"} layoutDependency={layoutDependency} layoutId={"zxRR1dag8"} ref={ref ?? ref1} style={{...style}}><motion.div className={"framer-1fadoq4"} layoutDependency={layoutDependency} layoutId={"gNzHLTQxC"} style={{backgroundColor: "var(--token-e67c061f-c1a4-4e26-a0c5-27e125470f23, rgb(242, 242, 242))", borderBottomLeftRadius: 48, borderBottomRightRadius: 48, borderTopLeftRadius: 48, borderTopRightRadius: 48}}><RichText __fromCanvasComponent children={<React.Fragment><motion.p className={"framer-styles-preset-5sgusm"} data-styles-preset={"xmi7mkoo2"}>12</motion.p></React.Fragment>} className={"framer-18itx5b"} fonts={["Inter"]} layoutDependency={layoutDependency} layoutId={"xDxaR_mhR"} style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"}} text={wwN2FoqAa} verticalAlignment={"top"} withExternalLayout/></motion.div><RichText __fromCanvasComponent children={<React.Fragment><motion.p className={"framer-styles-preset-1sp77s1"} data-styles-preset={"tTKYWLQt6"}>Years Experience</motion.p></React.Fragment>} className={"framer-1jc62qw"} fonts={["Inter"]} layoutDependency={layoutDependency} layoutId={"eDqvj86GT"} style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"}} text={w2mTfVwjE} verticalAlignment={"top"} withExternalLayout/></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-7uuAn.framer-xgcosf, .framer-7uuAn .framer-xgcosf { display: block; }", ".framer-7uuAn.framer-hxggjt { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 163px; }", ".framer-7uuAn .framer-1fadoq4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 96px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }", ".framer-7uuAn .framer-18itx5b, .framer-7uuAn .framer-1jc62qw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-7uuAn.framer-hxggjt, .framer-7uuAn .framer-1fadoq4 { gap: 0px; } .framer-7uuAn.framer-hxggjt > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } .framer-7uuAn.framer-hxggjt > :first-child, .framer-7uuAn .framer-1fadoq4 > :first-child { margin-top: 0px; } .framer-7uuAn.framer-hxggjt > :last-child, .framer-7uuAn .framer-1fadoq4 > :last-child { margin-bottom: 0px; } .framer-7uuAn .framer-1fadoq4 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }", ...sharedStyle.css, ...sharedStyle1.css]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 130
 * @framerIntrinsicWidth 163
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"wwN2FoqAa":"number","w2mTfVwjE":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerLqgdqDHos: React.ComponentType<Props> = withCSS(Component, css, "framer-7uuAn") as typeof Component;
export default FramerLqgdqDHos;

FramerLqgdqDHos.displayName = "Statistics Number";

FramerLqgdqDHos.defaultProps = {height: 130, width: 163};

addPropertyControls(FramerLqgdqDHos, {wwN2FoqAa: {defaultValue: "12", displayTextArea: false, title: "Number", type: ControlType.String}, w2mTfVwjE: {defaultValue: "Years Experience", displayTextArea: false, title: "Title", type: ControlType.String}} as any)

addFonts(FramerLqgdqDHos, [{explicitInter: true, fonts: [{family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F", url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+1F00-1FFF", url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0370-03FF", url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF", url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB", url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2", weight: "400"}]}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {supportsExplicitInterCodegen: true})