// Generated by Framer (9f68555)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-lF1yblCAO", breakpoints: [{hash: "amc1u9", mediaQuery: "(min-width: 1200px)"}, {hash: "ujnvcc", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "55ure0", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-UQqZE", title: siteMetadata(params, activeLocale).title || "Slideshow", viewport: "width=device-width"}
}

export const metadataVersion = 1