// Generated by Framer (e010222)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-cNo33wJtc", breakpoints: [{hash: "24od3m", mediaQuery: "(min-width: 1200px)"}, {hash: "11ol77d", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1mg6642", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {d8MXkw58_: "interior-design", f0ynBoHFM: "newsletter", lRf56nntf: "how-it-s-made-02", r2z1wLnBS: "commercial-design", uaqndgt8v: "residential-design", UcYJ65gjb: "how-it-s-made-01"}, robots: "max-image-preview:large", serializationId: "framer-xs0Hi", title: siteMetadata(params, activeLocale).title || "Project", viewport: "width=device-width"}
}

export const metadataVersion = 1