// Generated by Framer (ca9141d)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-s4nT1S2aU", breakpoints: [{hash: "6vqk2d", mediaQuery: "(min-width: 1200px)"}, {hash: "tk07t5", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1g7chbs", mediaQuery: "(max-width: 809px)"}], description: "EVIVE is a modern architectural design template crafted for creativity and functionality. Perfect for showcasing projects, services, and portfolios.", elements: {}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-T7Igj", title: "EVIVE - Arch Design Template", viewport: "width=device-width"}
}

export const metadataVersion = 1