// Generated by Framer (b4533c2)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1uhft60", mediaQuery: "(min-width: 1200px)"}, {hash: "10mmc6s", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1vdw97u", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {svOVVBJD6: "newsletter"}, robots: "max-image-preview:large", serializationId: "framer-XNPFj", title: siteMetadata(params, activeLocale).title || "Contact", viewport: "width=device-width"}
}

export const metadataVersion = 1