// Generated by Framer (ca9141d)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const Pg_y2qV1V = params?.Pg_y2qV1V
return {bodyClassName: "framer-body-hF42L0n1l", breakpoints: [{hash: "bg6t0n", mediaQuery: "(min-width: 1200px)"}, {hash: "q4btb0", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "15sndwi", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-Zltbs", title: `${Pg_y2qV1V !== undefined ? toString(Pg_y2qV1V) : "{{Pg_y2qV1V}}"} - My Framer Site`, viewport: "width=device-width"}
}

export const metadataVersion = 1