// Generated by Framer (b4533c2)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "72rtr7", mediaQuery: "(min-width: 1200px)"}, {hash: "11gomx6", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "u9qbbt", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {VPdmgghOS: "newsletter"}, robots: "max-image-preview:large", serializationId: "framer-pppFd", title: siteMetadata(params, activeLocale).title || "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1