// Generated by Framer (ca9141d)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-fEnbBBYQo", breakpoints: [{hash: "k1y9a3", mediaQuery: "(min-width: 1200px)"}, {hash: "3npiz6", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1rt16pe", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: false}, robots: "noindex", serializationId: "framer-tsRhL", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1