// Generated by Framer (ca9141d)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-xHlUT9xe0", breakpoints: [{hash: "kg4i7j"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-9wXCb", title: siteMetadata(params, activeLocale).title || "Page", viewport: "width=1200"}
}

export const metadataVersion = 1